### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by TheYoBots**
Directory was never got and it resulted in an error.

### CODE REVIEW

**Comment by TheYoBots** [comment]
But the file `stockfishmodern` is in the engine dir

**Comment by OIVAS7572** [comment]
look this line https://github.com/OIVAS7572/lichess-bot/blob/3c62e34972324d69b44dc508b1e4d4f73a847697/Dockerfile#L10

docker will copy files in `./engine` dir to `./` dir

**Comment by TheYoBots** [comment]
Oh ok, I’ll change that

**Comment by OIVAS7572** [comment]
if you change dir bot will not work

**Pull request merged**
