### PR TITLE
Update 18-03-2022

### PR DESCRIPTION
**Pull request by OIVAS7572**
Synced to 558th commit in https://github.com/ShailChoksi/lichess-bot

### CODE REVIEW

**Comment by TheYoBots** [comment]
If you don't want to force push, then you can simply copy paste the files from here https://github.com/OIVAS7572/lichess-bot/tree/ShailChoksi/lichess-bot-latest . This is the last commit, so only 2 commits need to be taken from shailchoksi/lichess-bot

**Comment by OIVAS7572** [comment]
@TheYoBots 
I created a script for copy pasting. check it

**Comment by TheYoBots** [comment]
Why do you need a script? It isn't hard to copy multiple files.

**Comment by OIVAS7572** [comment]
It is hard to copy paste the files

**Comment by OIVAS7572** [comment]
I think strategies.py is missing

**Comment by OIVAS7572** [comment]
@TheYoBots 
Just run `./update`
It will automatically update files from ShailChoksi

**Comment by OIVAS7572** [comment]
@TheYoBots 
I changed the `config.yml.default` to `config.yml` in Dockerfile.
Why pytest in Python workflow is still failing on Ubuntu?

**Comment by OIVAS7572** [comment]
@TheYoBots
One more request
We only need to build and test on the python 3.7 (version used in docker).
Isn't it?

**Comment by TheYoBots** [comment]
No, we need all version from python 3.7 onwards

**Comment by OIVAS7572** [comment]
It is still failing on python 3.10

**Comment by TheYoBots** [comment]
That's the test_bot files

**Pull request merged**
