### PR TITLE
Add CI Pipeline

### PR DESCRIPTION
**Pull request by TheYoBots**
For free GitHub can run tests with every commit:
https://github.com/features/actions

I’ve added the standard Python CI Pipeline.

### CODE REVIEW

**Comment by TheYoBots** [comment]
There was no requirement of fixing build scripts in this change, so it could be done with ease. :)

**Comment by TheYoBots** [comment]
I have created to CI Pipeline for Dockerfile too as was requested by you. It’s working well and is now in fit condition to be merged at your own will.

**Comment by TheYoBots** [comment]
I’ve added to CI Pipeline status badge to be clearly seen in the repository.

**Comment by TheYoBots** [comment]
To view how code will look and how it is running check:

1. https://github.com/TheYoBots/lichess-bot-1#maintainer-oivas7572 : To see how the docs will look after this change.

2. https://github.com/TheYoBots/lichess-bot-1/actions : To see how the CI Pipelines are running smoothly.

**Comment by OIVAS7572** [comment]
OK i will add Ci for docker

**Comment by OIVAS7572** [comment]
thank you very much

**Pull request merged**
