### PR TITLE
Major Update

### PR DESCRIPTION
**Pull request by OIVAS7572**
Update from `ShailChoksi` repo

### CODE REVIEW

**Comment by OIVAS7572** [comment]
@TheYoBots 
Please wait for any other changes (don't merge it now).
I prefer to do `Squash and Merge`.

**Comment by TheYoBots** [comment]
Is this ready yet? Or do you want me to make some changes or review this?

**Comment by OIVAS7572** [comment]
@TheYoBots 
I want to do latest changes from https://github.com/ShailChoksi/lichess-bot

**Comment by OIVAS7572** [comment]
@TheYoBots
Why you delete a line from dockerfile?

**Comment by SriMethan** [comment]
@OIVAS7572 because its not needed

**Comment by TheYoBots** [comment]
It isn't needed and also the nnue is directly downloaded with the engine.

**Pull request merged**
