### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by stockfish13**
Do this to make bot powerfull

### CODE REVIEW

**Comment by barca-cloud** [comment]
omg my bot is p0laying all moves at 1 mili second

**Comment by TheYoBots** [comment]
> Do this to make bot powerfull

That's for selecting challenges. Not related to got playing strength. Setting it to best is very unfair if many people are challenging the bot.

**Comment by thechugtyh** [comment]
so if we do then we can set change that bot can play 2 games in a row?

**Comment by thechugtyh** [comment]
@TheYoBots ??

**Comment by TheYoBots** [comment]
> so if we do then we can set change that bot can play 2 games in a row?

Increase concurrency for that.

**Comment by barca-cloud** [comment]
i know that so can i do that ??

**Comment by TheYoBots** [comment]
> i know that so can i do that ??

Your choice.

**Pull request closed without merging**
