### PR TITLE
Set Token In Heroku Config Vars

### PR DESCRIPTION
**Pull request by SriMethan**

### CODE REVIEW

**Comment by OIVAS7572** [comment]
@SriMethan 
Did you tested it.

**Comment by SriMethan** [comment]
yes

**Comment by SriMethan** [comment]
All OK

**Comment by SriMethan** [comment]
no it fails

**Comment by OIVAS7572** [comment]
@TheYoBots  
Did you tried this in heroku?

**Comment by TheYoBots** [comment]
> @TheYoBots Did you tried this in heroku?

Yes I did @OIVAS7572

**Pull request closed without merging**
