### PR TITLE
Bots can send greetings at start/end of game

### PR DESCRIPTION
**Pull request by lidevelopers**
Closes https://github.com/OIVAS7572/lichess-bot/issues/69 and completes https://github.com/OIVAS7572/lichess-bot/pull/70

### CODE REVIEW

**Comment by barca-cloud** [comment]
oh didnot see that hmm

**Comment by lidevelopers** [comment]
Still I didn't check that changes with my lichess bot when I checked and if it worked I'll send a pull request to your fork

**Comment by barca-cloud** [comment]
well can i try that thing if you dont mind i try

**Comment by thechugtyh** [comment]
well i made the bot like that but.. it wont say hi!

**Comment by TheYoBots** [comment]
Owners will do the necessary changes once it is merged in the official repository.

**Pull request closed without merging**
