### PR TITLE
Mega update

### PR DESCRIPTION
**Pull request by OIVAS7572**

### CODE REVIEW

**Comment by OIVAS7572** [comment]
@TheYoBots 
Why python checks are not passing?

**Comment by SriMethan** [comment]
The error is
```python
FileNotFoundError: [Errno 2] No such file or directory: './config.yml.default'
```
Because of
```python
with open("./config.yml.default") as file:
```
so you should change config.yml.default to config.yml
```python
with open("./config.yml) as file:
```

**Comment by SriMethan** [comment]
The error is
```python
FileNotFoundError: [Errno 2] No such file or directory: './config.yml.default'
```
Because of
```python
with open("./config.yml.default") as file:
```
so you should change config.yml.default to config.yml
```python
with open("./config.yml") as file:
```

**Comment by TheYoBots** [comment]
I could force push the update branch to master after further updating it, but i don't have access. I suggest you force push the updates branch into the master branch

**Comment by OIVAS7572** [comment]
image

@TheYoBots
How this came here?
How 24 participants appeared here?

**Pull request closed without merging**
