### PR TITLE
Merge upstream to branch `lczero`

### PR DESCRIPTION
**Pull request by TheYoBots**
To be merged by me. Please do not merge.

Also @OIVAS7572 please approve this pull request, but don’t merge.

### CODE REVIEW

**Comment by TheYoBots** [comment]
@OIVAS7572 can you please disable the `review required` thing?

**Comment by OIVAS7572** [comment]
keep "maintainer" capital letters
I think engine is Lc0
there are some Conflicting files
I removed review required, keep repo safe

**Review by OIVAS7572 — APPROVED** [review]

**Comment by OIVAS7572** [comment]
@TheYoBots 
Bot is made with Python and it is running using Docker container.

**Comment by TheYoBots** [comment]
I made it `Maintainer` Instead of `MAINTAINER` as reading CAPS is very unpleasant for the eyes and looks a bit annoying and rude, but if you want to keep it all CAPS then it’s your choice. Yes I know there are merge conflicts, it will be resolved when I need to merge this pull request.

**Comment by OIVAS7572** [comment]
**what a magic, this repo reached 100 forks ?
Thanks to all contributers and those for who recommended my repo**

**Comment by OIVAS7572** [comment]
> I made it `Maintainer` Instead of `MAINTAINER` as reading CAPS is very unpleasant for the eyes and looks a bit annoying and rude, but if you want to keep it all CAPS then it’s your choice. Yes I know there are merge conflicts, it will be resolved when I need to merge this pull request.

i need it caps but I reduced it's size now I changed to three hashes now

**Comment by TheYoBots** [comment]
> > I made it `Maintainer` Instead of `MAINTAINER` as reading CAPS is very unpleasant for the eyes and looks a bit annoying and rude, but if you want to keep it all CAPS then it’s your choice. Yes I know there are merge conflicts, it will be resolved when I need to merge this pull request.
> 
> i need it caps but I reduced it's size now I changed to three hashes now

Can we make it bold instead of `###`?

**Comment by OIVAS7572** [comment]
I noticed One thing, NoBody is updating their forks
Is there any solution to this to keep repo uptodate

**Comment by TheYoBots** [comment]
> I noticed One thing, NoBody is updating their forks
> Is there any solution to this to keep repo uptodate

I’ll create a wiki or gist explaining how to update a repository.

**Comment by OIVAS7572** [comment]
> > > I made it `Maintainer` Instead of `MAINTAINER` as reading CAPS is very unpleasant for the eyes and looks a bit annoying and rude, but if you want to keep it all CAPS then it’s your choice. Yes I know there are merge conflicts, it will be resolved when I need to merge this pull request.
> > 
> > 
> > i need it caps but I reduced it's size now I changed to three hashes now
> 
> Can we make it bold instead of `###`?

ok
then it should be in first line

**Comment by OIVAS7572** [comment]
> > I noticed One thing, NoBody is updating their forks
> > Is there any solution to this to keep repo uptodate
> 
> I’ll create a wiki or gist explaining how to update a repository.

say that to users through readme.md
means keep link to gist or wiki in readme.md

**Comment by OIVAS7572** [comment]
Did i need to update this repo's code from shailChoksi's they updated their repo. is there any essential changes in shailChoksi's repo

**Comment by TheYoBots** [comment]
> @TheYoBots
> Did i need to update this repo's code from shailChoksi's they updated their repo. is there any essential changes in shailChoksi's repo

I’ll check that out and tell you

**Pull request merged**
