### PR TITLE
Merge Upstream

### LINKED ISSUE #142: stockfish 15 also add matchmaking
will you all upgrade to stockfish 15 and also dev? and yes will we ever get https://github.com/ShailChoksi/lichess-bot/pull/473#partial-pull-merging ? this here?

### PR DESCRIPTION
**Pull request by TheYoBots**
Closes #142

### CODE REVIEW

**Review by thechipsss — APPROVED** [review]

**Review by OIVAS7572 — APPROVED** [review]
Good

**Review by OIVAS7572 — CHANGES_REQUESTED** [review]
Change MEGA to main in Dockerfile

**Review by OIVAS7572 — APPROVED** [review]

**Review by SriMethan — APPROVED** [review]

**Comment by OIVAS7572** [comment]
@TheYoBots 
When it will be merged?

**Comment by TheYoBots** [comment]
Once the matchmaking pr is merged in ShailChoksi/lichess-bot

**Comment by SriMethan** [comment]
It seems that still matchmaking pr in ShailChoksi/lichess-bot is not merged yet.

**Comment by thechipsss** [comment]
When will it get merged?

**Pull request merged**
